using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Threading;

namespace GeneratorFromAttribute;

[Generator(LanguageNames.CSharp)]
public sealed class GeneratorFromAttributeClass : IIncrementalGenerator
{
    private static readonly string generatedCodeAttribute = $@"[global::System.CodeDom.Compiler.GeneratedCodeAttribute(""{typeof(GeneratorFromAttributeClass).Assembly.GetName().Name}"", ""{typeof(GeneratorFromAttributeClass).Assembly.GetName().Version}"")]";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        //if (!Debugger.IsAttached) Debugger.Launch();
        context.RegisterPostInitializationOutput(GenerateFixedClasses);

        IncrementalValuesProvider<(string TypeName, Accessibility ClassAccessibility, string? Namespaces, MasterType masterType)> provider =
            context.SyntaxProvider.ForAttributeWithMetadataName(
                "GeneratorFromAttributeExample.GenerateSetPropertyAttribute`1",
                predicate: FilterClass,
                transform: CreateObjCollection);

        var collectedClasses = provider.Collect();
        context.RegisterSourceOutput(collectedClasses, CreateSourceCode!);
    }

    private static void GenerateFixedClasses(IncrementalGeneratorPostInitializationContext context)
    {
        //language=c#
        string source = $$"""
            // <auto-generated/>
            #nullable enable
            using System;
            namespace GeneratorFromAttributeExample;

            {{generatedCodeAttribute}}
            [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
            internal sealed class GenerateSetPropertyAttribute<T>() : global::System.Attribute where T : class
            {}

            {{generatedCodeAttribute}}
            public static class ConversionHelper
            {
                public static T Parsex<T>(string str) where T : IParsable<T> => T.Parse(str, null);
            }
            """;

        var fileName = "GeneratorFromAttributeExample.GenerateSetPropertyAttribute.g.cs";
        context.AddSource(fileName, source);
    }


    private static bool FilterClass(SyntaxNode node, CancellationToken cancellationToken) =>
        node is ClassDeclarationSyntax;

    private static (string TypeName, Accessibility ClassAccessibility, string? Namespaces, MasterType masterType) CreateObjCollection(GeneratorAttributeSyntaxContext context, CancellationToken _)
    {
        //if (!Debugger.IsAttached) Debugger.Launch();
        var symbol = (INamedTypeSymbol)context.TargetSymbol;
        var className = symbol.Name;

        var classDeclarationSyntax = (ClassDeclarationSyntax)context.TargetNode;
        var isPartial = classDeclarationSyntax.Modifiers.Any(SyntaxKind.PartialKeyword);
        var isStatic = classDeclarationSyntax.Modifiers.Any(SyntaxKind.StaticKeyword);

        var namespacesClass = string.IsNullOrEmpty(symbol.ContainingNamespace.Name) ? null : symbol.ContainingNamespace.ToDisplayString();
        MasterType masterType = new(className, isPartial, isStatic);
        List<string> classNames = [];

        foreach (var attributeData in context.Attributes)
        {
            var attributeType = attributeData.AttributeClass!;
            var typeArguments = attributeType.TypeArguments;
            var typeSymbol = typeArguments[0];
            if (classNames.Contains(typeSymbol.Name)) continue;
            classNames.Add(typeSymbol.Name);

            var ns = string.IsNullOrEmpty(typeSymbol.ContainingNamespace.Name) ? null : typeSymbol.ContainingNamespace.ToDisplayString();
            var properties = typeSymbol.GetMembers()
                .OfType<IPropertySymbol>()
                .Select(t => new SubProperty(t.Name, t.Type)).ToList();

            masterType.SubTypes.Add(new SubTypeClass(
                typeSymbol.Name,
                ns,
                properties)
            );
        }

        return (className, symbol.DeclaredAccessibility, namespacesClass, masterType);
    }

    private static void CreateSourceCode(SourceProductionContext ctx, ImmutableArray<(string TypeName, Accessibility ClassAccessibility, string Namespaces, MasterType MasterType)> collectedClasses)
    {
        //if (!Debugger.IsAttached) Debugger.Launch();
        foreach (var info in collectedClasses)
        {
            if (!info.MasterType.IsPartial || !info.MasterType.IsStatic)
            {
                Helper.ReportClassNotSupportedDiagnostic(ctx, info.MasterType.ClassName);
                continue;
            }

            using StringWriter writer = new(CultureInfo.InvariantCulture);
            using IndentedTextWriter tx = new(writer);

            tx.WriteLine("// <auto-generated/>");
            tx.WriteLine("#nullable enable");
            tx.WriteLine();
            tx.WriteLine("using System.Globalization;");
            tx.WriteLine("using GeneratorFromAttributeExample;");

            if (!string.IsNullOrEmpty(info.Namespaces))
            {
                tx.WriteLine($"namespace {info.Namespaces}");
                tx.WriteLine('{');
                tx.Indent++;
            }

            tx.WriteLine($"[global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"{typeof(GeneratorFromAttributeClass).Assembly.GetName().Name}\", \"{typeof(GeneratorFromAttributeClass).Assembly.GetName().Version}\")]");
            tx.WriteLine($"{SyntaxFacts.GetText(info.ClassAccessibility)} static partial class {info.TypeName}");
            tx.WriteLine('{');
            tx.Indent++;

            foreach (var subType in info.MasterType.SubTypes)
            {
                var ns = string.IsNullOrEmpty(subType.Namespace) ? string.Empty : subType.Namespace! + ".";
                tx.WriteLine($"{SyntaxFacts.GetText(info.ClassAccessibility)} static void SetProperties{subType.Classname}({ns}{subType.Classname} obj, string[] values)");
                tx.WriteLine('{');
                tx.Indent++;
                InsertPropertiesInSwitch(ctx, tx, subType);
                tx.Indent--;
                tx.WriteLine('}');
                tx.WriteLine();
            }

            tx.Indent--;
            tx.WriteLine('}');
            if (!string.IsNullOrEmpty(info.Namespaces))
            {
                tx.Indent--;
                tx.WriteLine('}');
            }

            Debug.Assert(tx.Indent == 0);
            ctx.AddSource($"{info.TypeName}.g.cs", writer.ToString());
        }
    }

    private static void InsertPropertiesInSwitch(SourceProductionContext context, IndentedTextWriter tx, SubTypeClass subType)
    {
        for (var counter = 0; counter < subType.Properties.Count; counter++)
        {
            var property = subType.Properties[counter];

            var clrType = Helper.GetClrTypeName(property.Type);

            tx.WriteLine((clrType.TypeClr, clrType.IsNullable) switch
            {
                (Helper.TypeClr.DateTime, false) => $"obj.{property.Name} = DateTime.Parse(values[{counter}]!);",
                (Helper.TypeClr.DateTime, true) => $"obj.{property.Name} = DateTime.Parse(values[{counter}]!);",
                (Helper.TypeClr.Number, true) => $"obj.{property.Name} = ConversionHelper.Parsex<{clrType.TypeString}>(values[{counter}]!);",
                (Helper.TypeClr.Number, false) => $"obj.{property.Name} = ConversionHelper.Parsex<{clrType.TypeString}>(values[{counter}]!);",
                (Helper.TypeClr.String, true) => $"obj.{property.Name} = values[{counter}];",
                _ => $"obj.{property.Name} = values[{counter}];"
            });
        }
    }
}